name: findx_dart_client
description: data client for the application
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  graphql: ^5.1.3
  dio: ^5.3.3
  meta: ^1.10.0

  app_client:
    git:
      url: git@github.com:FindX-0/findx_dart_client.git
      path: packages/app_client

  gql_types:
    git:
      url: git@github.com:FindX-0/findx_dart_client.git
      path: packages/gql_types

  common_models:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_models

dev_dependencies:
  flutter_lints: ^3.0.1
