enum GqlApiErrorCode {
  unknown,
  missingToken,
  expiredToken,
  invalidToken,
  emailOrPasswordInvalid,
  userEmailExists,
  adminUserEmailExists,
  userNotFound,
  refreshTokenReuse,
  recoverPasswordRequestNotFound,
  recoverPasswordRequestInvalidCode,
  recoverPasswordRequestTimedOut,
  recoverPasswordRequestInvalid,
  accountVerifficationRequestNotFound,
  missingAuthUserPayload,
  invalidRequest,
  cantSignInWithGoogle,
  googleOauthAccessTokenIsExpired,
  couldNotCreateUser,
  couldNotCreateMathField,
  couldNotCreateAdminUser,
  mathFieldNotFound,
  mathSubFieldNotFound,
  adminUserNotFound,
  couldNotCreateMediaFile,
  mediaFileNotFound,
  ticketNotFound,
  mathFieldHasRelations,
  mathSubFieldHasRelations;

  static GqlApiErrorCode fromApiString(String code) {
    return switch (code) {
      'MISSING_TOKEN' => GqlApiErrorCode.missingToken,
      'EXPIRED_TOKEN' => GqlApiErrorCode.expiredToken,
      'INVALID_TOKEN' => GqlApiErrorCode.invalidToken,
      'EMAIL_OR_PASSWORD_INVALID' => GqlApiErrorCode.emailOrPasswordInvalid,
      'USER_EMAIL_EXISTS' => GqlApiErrorCode.userEmailExists,
      'ADMIN_USER_EMAIL_EXISTS' => GqlApiErrorCode.adminUserEmailExists,
      'USER_NOT_FOUND' => GqlApiErrorCode.userNotFound,
      'REFRESH_TOKEN_REUSE' => GqlApiErrorCode.refreshTokenReuse,
      'RECOVER_PASSWORD_REQUEST_NOT_FOUND' => GqlApiErrorCode.recoverPasswordRequestNotFound,
      'RECOVER_PASSWORD_REQUEST_INVALID_CODE' => GqlApiErrorCode.recoverPasswordRequestInvalidCode,
      'RECOVER_PASSWORD_REQUEST_TIMED_OUT' => GqlApiErrorCode.recoverPasswordRequestTimedOut,
      'RECOVER_PASSWORD_REQUEST_INVALID' => GqlApiErrorCode.recoverPasswordRequestInvalid,
      'ACCOUNT_VERIFFICATION_REQUEST_NOT_FOUND' => GqlApiErrorCode.accountVerifficationRequestNotFound,
      'MISSING_AUTH_USER_PAYLOAD' => GqlApiErrorCode.missingAuthUserPayload,
      'INVALID_REQUEST' => GqlApiErrorCode.invalidRequest,
      'CANT_SIGN_IN_WITH_GOOGLE' => GqlApiErrorCode.cantSignInWithGoogle,
      'GOOGLE_OAUTH_ACCESS_TOKEN_IS_EXPIRED' => GqlApiErrorCode.googleOauthAccessTokenIsExpired,
      'COULD_NOT_CREATE_USER' => GqlApiErrorCode.couldNotCreateUser,
      'COULD_NOT_CREATE_MATH_FIELD' => GqlApiErrorCode.couldNotCreateMathField,
      'COULD_NOT_CREATE_ADMIN_USER' => GqlApiErrorCode.couldNotCreateAdminUser,
      'MATH_FIELD_NOT_FOUND' => GqlApiErrorCode.mathFieldNotFound,
      'MATH_SUB_FIELD_NOT_FOUND' => GqlApiErrorCode.mathSubFieldNotFound,
      'ADMIN_USER_NOT_FOUND' => GqlApiErrorCode.adminUserNotFound,
      'COULD_NOT_CREATE_MEDIA_FILE' => GqlApiErrorCode.couldNotCreateMediaFile,
      'MEDIA_FILE_NOT_FOUND' => GqlApiErrorCode.mediaFileNotFound,
      'TICKET_NOT_FOUND' => GqlApiErrorCode.ticketNotFound,
      'MATH_FIELD_HAS_RELATIONS' => GqlApiErrorCode.mathFieldHasRelations,
      'MATH_SUB_FIELD_HAS_RELATIONS' => GqlApiErrorCode.mathSubFieldHasRelations,
      _ => GqlApiErrorCode.unknown,
    };
  }
}
