targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scalars:
            DateTime:
              type: DateTime
            JSON:
              type: Map<String, dynamic>
          clients:
            - graphql
